version: "3"
services:
  # app:
  #   image: task-list-api
  #   ports:
  #     - "80:3000"
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
  adminer:
    image: adminer
    ports:
      - "8080:8080"