export const DEFAULT_MAX_SESSION_COUNT = 1000;
export const DEFAULT_MAX_TASKS_COUNT = 500000;
export const DEFAULT_MAX_TASKS_PER_SESSION = 500;

export const DEFAULT_POST_PUT_DELETE_LIMIT = 30;
export const DEFAULT_POST_PUT_DELETE_TTL = 60;

export const DEFAULT_GET_LIMIT = 200;
export const DEFAULT_GET_TTL = 60;

export const DEFAULT_SESSION_POST_LIMIT = 1;
export const DEFAULT_SESSION_POST_TTL = 20;

export const DEFAULT_CRON_PATTERN = '0 */6 * * *';
